name: Build and Release

on:
  push:
    branches: [ main, develop ]  # 任何推送到main或develop分支都触发
  pull_request:
    branches: [ main ]  # PR合并也触发
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Convert PNG to ICO (if needed)
      run: |
        if (!(Test-Path "resources\icons\tray_icon.ico")) {
          echo "Converting PNG to ICO format..."
          # 如果没有ico文件，可以使用在线转换或其他工具
          # 这里先跳过，使用PNG文件
        }
        
    - name: Build executable with spec
      run: |
        pyinstaller TimeNest.spec --clean --noconfirm
        
    - name: Create portable package
      run: |
        mkdir TimeNest-portable
        copy dist\TimeNest.exe TimeNest-portable\
        copy README.md TimeNest-portable\
        copy LICENSE TimeNest-portable\
        if (Test-Path "config") { xcopy /E /I config TimeNest-portable\config }
        if (Test-Path "resources") { xcopy /E /I resources TimeNest-portable\resources }
        if (Test-Path "themes") { xcopy /E /I themes TimeNest-portable\themes }
        if (Test-Path "schedule_template.xlsx") { copy schedule_template.xlsx TimeNest-portable\ }
        
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path TimeNest-portable\* -DestinationPath TimeNest-${{ github.ref_name }}-windows.zip
        
    - name: Get release info
      id: release_info
      run: |
        $tag = "${{ github.ref_name }}"
        $version = $tag -replace '^v', ''
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "tag=$tag" >> $env:GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: TimeNest ${{ steps.release_info.outputs.version }}
        body: |
          ## TimeNest ${{ steps.release_info.outputs.version }}
          
          ### 📦 下载
          - **Windows 便携版**: TimeNest-${{ steps.release_info.outputs.tag }}-windows.zip
          
          ### 🚀 新功能
          - 请在此处添加新功能描述
          
          ### 🐛 修复
          - 请在此处添加bug修复描述
          
          ### 📋 安装说明
          1. 下载 ZIP 文件
          2. 解压到任意目录
          3. 运行 TimeNest.exe
          
          ### 💡 系统要求
          - Windows 10/11
          - .NET Framework 4.7.2 或更高版本
          
          ### ⚠️ 注意事项
          这是一个预览版本，可能包含未完成的功能或已知问题。建议在非生产环境中使用。
        draft: false
        prerelease: ${{ contains(steps.release_info.outputs.version, 'Preview') || contains(steps.release_info.outputs.version, 'Beta') || contains(steps.release_info.outputs.version, 'RC') }}
        files: |
          TimeNest-${{ github.ref_name }}-windows.zip